{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4f1f911b-7c53-42c9-bf09-ae4cb960ab3f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q1\n",
    "In Python, when creating a custom exception, it is recommended to inherit from the base Exception class or \n",
    "one of its subclasses. This is because the Exception class provides a solid foundation and a set of common \n",
    "behaviors and attributes that are essential for an exception class.\n",
    "\n",
    "Here are a few reasons why we use the Exception class as the base for custom exceptions:\n",
    "\n",
    "1. Inheritance: By inheriting from the Exception class, our custom exception inherits all the properties, \n",
    "methods, and behaviors defined in the base class. This includes important attributes like args, which stores\n",
    "the arguments passed to the exception, and methods like __str__ for providing a string representation of the \n",
    "exception.\n",
    "\n",
    "2. Compatibility: Inheriting from the Exception class ensures that our custom exception is compatible with the \n",
    "existing exception handling mechanisms in Python. Since the built-in exception classes also inherit from Exception,\n",
    "our custom exception can be caught and handled using the same exception handling constructs, such as try-except blocks.\n",
    "\n",
    "3. Consistency: By adhering to the common practice of inheriting from Exception, we maintain consistency with other \n",
    "exception classes in Python. It makes our code more understandable for other developers who are familiar with the \n",
    "standard exception hierarchy and encourages adherence to established conventions.\n",
    "\n",
    "4. Standardized Behavior: The Exception class provides a consistent interface and behavior for exceptions in Python.\n",
    "It ensures that our custom exception class follows the expected conventions and can be used interchangeably with other\n",
    "exceptions.\n",
    "\n",
    "While it is technically possible to create a custom exception without inheriting from Exception, doing so may lead \n",
    "to inconsistent behavior, compatibility issues, and confusion among developers. By using Exception as the base class, \n",
    "we ensure that our custom exception aligns with the established exception handling practices and integrates smoothly \n",
    "with the existing exception infrastructure in Python."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "caa60a44-35e1-49cf-8188-e0edb3527462",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f6cb5aa8-14ae-46b4-b6bf-ca42bffecff6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception\n",
      "    TypeError\n",
      "        FloatOperation\n",
      "        MultipartConversionError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    ImportError\n",
      "        ModuleNotFoundError\n",
      "        ZipImportError\n",
      "    OSError\n",
      "        ConnectionError\n",
      "            BrokenPipeError\n",
      "            ConnectionAbortedError\n",
      "            ConnectionRefusedError\n",
      "            ConnectionResetError\n",
      "                RemoteDisconnected\n",
      "        BlockingIOError\n",
      "        ChildProcessError\n",
      "        FileExistsError\n",
      "        FileNotFoundError\n",
      "        IsADirectoryError\n",
      "        NotADirectoryError\n",
      "        InterruptedError\n",
      "            InterruptedSystemCall\n",
      "        PermissionError\n",
      "        ProcessLookupError\n",
      "        TimeoutError\n",
      "        UnsupportedOperation\n",
      "        itimer_error\n",
      "        herror\n",
      "        gaierror\n",
      "        SSLError\n",
      "            SSLCertVerificationError\n",
      "            SSLZeroReturnError\n",
      "            SSLWantWriteError\n",
      "            SSLWantReadError\n",
      "            SSLSyscallError\n",
      "            SSLEOFError\n",
      "        Error\n",
      "            SameFileError\n",
      "        SpecialFileError\n",
      "        ExecError\n",
      "        ReadError\n",
      "        URLError\n",
      "            HTTPError\n",
      "            ContentTooShortError\n",
      "        BadGzipFile\n",
      "    EOFError\n",
      "        IncompleteReadError\n",
      "    RuntimeError\n",
      "        RecursionError\n",
      "        NotImplementedError\n",
      "            ZMQVersionError\n",
      "            StdinNotImplementedError\n",
      "        _DeadlockError\n",
      "        BrokenBarrierError\n",
      "        BrokenExecutor\n",
      "            BrokenThreadPool\n",
      "        SendfileNotAvailableError\n",
      "        ExtractionError\n",
      "        VariableError\n",
      "    NameError\n",
      "        UnboundLocalError\n",
      "    AttributeError\n",
      "        FrozenInstanceError\n",
      "    SyntaxError\n",
      "        IndentationError\n",
      "            TabError\n",
      "    LookupError\n",
      "        IndexError\n",
      "        KeyError\n",
      "            NoSuchKernel\n",
      "            UnknownBackend\n",
      "        CodecRegistryError\n",
      "    ValueError\n",
      "        UnicodeError\n",
      "            UnicodeEncodeError\n",
      "            UnicodeDecodeError\n",
      "            UnicodeTranslateError\n",
      "        UnsupportedOperation\n",
      "        JSONDecodeError\n",
      "        SSLCertVerificationError\n",
      "        Error\n",
      "        UnsupportedDigestmodError\n",
      "        IllegalMonthError\n",
      "        IllegalWeekdayError\n",
      "        ParserError\n",
      "        ClassNotFound\n",
      "        ClipboardEmpty\n",
      "        MessageDefect\n",
      "            NoBoundaryInMultipartDefect\n",
      "            StartBoundaryNotFoundDefect\n",
      "            CloseBoundaryNotFoundDefect\n",
      "            FirstHeaderLineIsContinuationDefect\n",
      "            MisplacedEnvelopeHeaderDefect\n",
      "            MissingHeaderBodySeparatorDefect\n",
      "            MultipartInvariantViolationDefect\n",
      "            InvalidMultipartContentTransferEncodingDefect\n",
      "            UndecodableBytesDefect\n",
      "            InvalidBase64PaddingDefect\n",
      "            InvalidBase64CharactersDefect\n",
      "            InvalidBase64LengthDefect\n",
      "            HeaderDefect\n",
      "                InvalidHeaderDefect\n",
      "                HeaderMissingRequiredValue\n",
      "                NonPrintableDefect\n",
      "                ObsoleteHeaderDefect\n",
      "                NonASCIILocalPartDefect\n",
      "                InvalidDateDefect\n",
      "        MacroToEdit\n",
      "        InvalidFileException\n",
      "        UnequalIterablesError\n",
      "        InvalidVersion\n",
      "        _InvalidELFFileHeader\n",
      "        InvalidWheelFilename\n",
      "        InvalidSdistFilename\n",
      "        InvalidSpecifier\n",
      "        InvalidMarker\n",
      "        UndefinedComparison\n",
      "        UndefinedEnvironmentName\n",
      "        InvalidRequirement\n",
      "            RequirementParseError\n",
      "        InvalidVersion\n",
      "    AssertionError\n",
      "    ArithmeticError\n",
      "        FloatingPointError\n",
      "        OverflowError\n",
      "        ZeroDivisionError\n",
      "            DivisionByZero\n",
      "            DivisionUndefined\n",
      "        DecimalException\n",
      "            Clamped\n",
      "            Rounded\n",
      "                Underflow\n",
      "                Overflow\n",
      "            Inexact\n",
      "                Underflow\n",
      "                Overflow\n",
      "            Subnormal\n",
      "                Underflow\n",
      "            DivisionByZero\n",
      "            FloatOperation\n",
      "            InvalidOperation\n",
      "                ConversionSyntax\n",
      "                DivisionImpossible\n",
      "                DivisionUndefined\n",
      "                InvalidContext\n",
      "    SystemError\n",
      "        CodecRegistryError\n",
      "    ReferenceError\n",
      "    MemoryError\n",
      "    BufferError\n",
      "    Warning\n",
      "        UserWarning\n",
      "            GetPassWarning\n",
      "            FormatterWarning\n",
      "        EncodingWarning\n",
      "        DeprecationWarning\n",
      "            ProvisionalWarning\n",
      "        PendingDeprecationWarning\n",
      "        SyntaxWarning\n",
      "        RuntimeWarning\n",
      "            ProactorSelectorThreadWarning\n",
      "            UnknownTimezoneWarning\n",
      "            PEP440Warning\n",
      "        FutureWarning\n",
      "            ProvisionalCompleterWarning\n",
      "        ImportWarning\n",
      "        UnicodeWarning\n",
      "        BytesWarning\n",
      "        ResourceWarning\n",
      "        DeprecatedTzFormatWarning\n",
      "        PkgResourcesDeprecationWarning\n",
      "    _OptionError\n",
      "    _Error\n",
      "    error\n",
      "    Verbose\n",
      "    Error\n",
      "    SubprocessError\n",
      "        CalledProcessError\n",
      "        TimeoutExpired\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    TraitError\n",
      "    Error\n",
      "    Error\n",
      "        CancelledError\n",
      "        TimeoutError\n",
      "        InvalidStateError\n",
      "    _GiveupOnSendfile\n",
      "    error\n",
      "    Incomplete\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    Empty\n",
      "    Full\n",
      "    ArgumentError\n",
      "    ZMQBaseError\n",
      "        ZMQError\n",
      "            ContextTerminated\n",
      "            Again\n",
      "            InterruptedSystemCall\n",
      "        ZMQBindError\n",
      "        NotDone\n",
      "    PickleError\n",
      "        PicklingError\n",
      "        UnpicklingError\n",
      "    _Stop\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "        ConfigLoaderError\n",
      "            ArgumentError\n",
      "        ConfigFileNotFound\n",
      "    ConfigurableError\n",
      "        MultipleInstanceError\n",
      "    ApplicationError\n",
      "    error\n",
      "    TimeoutError\n",
      "    error\n",
      "    ReturnValueIgnoredError\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    InvalidPortNumber\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    Error\n",
      "        NoSectionError\n",
      "        DuplicateSectionError\n",
      "        DuplicateOptionError\n",
      "        NoOptionError\n",
      "        InterpolationError\n",
      "            InterpolationMissingOptionError\n",
      "            InterpolationSyntaxError\n",
      "            InterpolationDepthError\n",
      "        ParsingError\n",
      "            MissingSectionHeaderError\n",
      "    NoIPAddresses\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    BadEntryPoint\n",
      "    NoSuchEntryPoint\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    NotOneValueFound\n",
      "    CannotEval\n",
      "    OptionError\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    ExceptionPexpect\n",
      "        EOF\n",
      "        TIMEOUT\n",
      "    PtyProcessError\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "        TryNext\n",
      "        UsageError\n",
      "        StdinNotImplementedError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "        InvalidAliasError\n",
      "    Error\n",
      "        InterfaceError\n",
      "        DatabaseError\n",
      "            InternalError\n",
      "            OperationalError\n",
      "            ProgrammingError\n",
      "            IntegrityError\n",
      "            DataError\n",
      "            NotSupportedError\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "        IndexSizeErr\n",
      "        DomstringSizeErr\n",
      "        HierarchyRequestErr\n",
      "        WrongDocumentErr\n",
      "        InvalidCharacterErr\n",
      "        NoDataAllowedErr\n",
      "        NoModificationAllowedErr\n",
      "        NotFoundErr\n",
      "        NotSupportedErr\n",
      "        InuseAttributeErr\n",
      "        InvalidStateErr\n",
      "        SyntaxErr\n",
      "        InvalidModificationErr\n",
      "        NamespaceErr\n",
      "        InvalidAccessErr\n",
      "        ValidationErr\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "        InternalError\n",
      "        WrongVersion\n",
      "        RefactoringError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    MessageError\n",
      "        MessageParseError\n",
      "            HeaderParseError\n",
      "            BoundaryError\n",
      "        MultipartConversionError\n",
      "        CharsetError\n",
      "    Error\n",
      "    HTTPException\n",
      "        NotConnected\n",
      "        InvalidURL\n",
      "        UnknownProtocol\n",
      "        UnknownTransferEncoding\n",
      "        UnimplementedFileMode\n",
      "        IncompleteRead\n",
      "        ImproperConnectionState\n",
      "            CannotSendRequest\n",
      "            CannotSendHeader\n",
      "            ResponseNotReady\n",
      "        BadStatusLine\n",
      "            RemoteDisconnected\n",
      "        LineTooLong\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "        NoSuchProcess\n",
      "            ZombieProcess\n",
      "        AccessDenied\n",
      "        TimeoutExpired\n",
      "    _Ipv6UnsupportedError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    DebuggerInitializationError\n",
      "    ExpatError\n",
      "    Error\n",
      "        ProtocolError\n",
      "        ResponseError\n",
      "        Fault\n",
      "    ParseBaseException\n",
      "        ParseException\n",
      "        ParseFatalException\n",
      "            ParseSyntaxException\n",
      "    RecursiveGrammarException\n",
      "    ResolutionError\n",
      "        VersionConflict\n",
      "            ContextualVersionConflict\n",
      "        DistributionNotFound\n",
      "        UnknownExtra\n",
      "    _Error\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n"
     ]
    }
   ],
   "source": [
    "#Q2\n",
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' ' * indent + f'{exception_class.__name__}')\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent + 4)\n",
    "\n",
    "# Print the Exception Hierarchy starting from the base Exception class\n",
    "print_exception_hierarchy(Exception)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "60cc163f-19ee-4cad-a708-86f6b70a9280",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "77bbd091-0ec5-4b39-bc2f-f692db528173",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q3\n",
    "The ArithmeticError class in Python is the base class for all errors related to arithmetic operations. \n",
    "It is a subclass of the Exception class and provides a common base for specific arithmetic-related \n",
    "exception classes.\n",
    "\n",
    "1. ZeroDivisionError: This error is raised when an attempt is made to divide a number by zero.\n",
    "2. OverflowError: This error is raised when the result of an arithmetic operation exceeds the maximum\n",
    "                  representable value."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3647fa4c-09aa-4838-89ed-d938f1d61388",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Division result: 5.0\n",
      "Error: Division by zero is not allowed.\n"
     ]
    }
   ],
   "source": [
    "#ZeroDivisionError\n",
    "def divide(a, b):\n",
    "    try:\n",
    "        result = a / b\n",
    "        print(\"Division result:\", result)\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Error: Division by zero is not allowed.\")\n",
    "\n",
    "# Calling the divide function\n",
    "divide(10, 2)  # Valid division\n",
    "divide(10, 0)  # Division by zero\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "14775981-e6e8-4d48-a881-0e37f31ee93f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "5.0\n",
      "25.0\n",
      "15625.0\n",
      "5.960464477539062e+16\n",
      "7.52316384526264e+83\n",
      "Overflow error happened\n"
     ]
    }
   ],
   "source": [
    "#OverflowError\n",
    "j = 5.0\n",
    "\n",
    "try:\n",
    "    for i in range(1, 1000):\n",
    "        j = j**i\n",
    "        print(j)\n",
    "except OverflowError as e:\n",
    "    print(\"Overflow error happened\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4eefde16-f83e-4681-8277-ba430f37a758",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6ef94150-8517-4c2f-b036-e82655a73004",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q4\n",
    "The LookupError class in Python is the base class for exceptions that occur when an invalid key or \n",
    "index is used to access a collection, such as a dictionary or a list. It is a subclass of the Exception \n",
    "class and provides a common base for specific lookup-related exception classes.\n",
    "\n",
    "Two commonly encountered exceptions that are derived from LookupError are KeyError and IndexError.\n",
    "\n",
    "1. KeyError: This exception is raised when a dictionary key is not found.\n",
    "2. IndexError: This exception is raised when an invalid index is used to access a list or a sequence."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "622ee35b-3d94-492d-b20f-d11369d8460c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Value: John\n",
      "Error: Key not found in the dictionary.\n"
     ]
    }
   ],
   "source": [
    "#KeyError\n",
    "def access_dictionary(dictionary, key):\n",
    "    try:\n",
    "        value = dictionary[key]\n",
    "        print(\"Value:\", value)\n",
    "    except KeyError:\n",
    "        print(\"Error: Key not found in the dictionary.\")\n",
    "\n",
    "# Dictionary\n",
    "my_dict = {\"name\": \"John\", \"age\": 25, \"city\": \"New York\"}\n",
    "\n",
    "# Accessing dictionary elements\n",
    "access_dictionary(my_dict, \"name\")  # Valid key\n",
    "try:\n",
    "    access_dictionary(my_dict, \"gender\")  # Key not found\n",
    "except KeyError:\n",
    "    pass\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b98b28a2-5e8f-412a-b2c1-97a1968deefc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Value: 30\n",
      "Error: Invalid index for the list.\n"
     ]
    }
   ],
   "source": [
    "#IndexError\n",
    "def access_list(lst, index):\n",
    "    try:\n",
    "        value = lst[index]\n",
    "        print(\"Value:\", value)\n",
    "    except IndexError:\n",
    "        print(\"Error: Invalid index for the list.\")\n",
    "\n",
    "# List\n",
    "my_list = [10, 20, 30, 40, 50]\n",
    "\n",
    "# Accessing list elements\n",
    "access_list(my_list, 2)  # Valid index\n",
    "access_list(my_list, 10)  # Invalid index\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9eac68ed-a5fc-41b2-8c50-c24ecc18a786",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7a29cd79-ea84-48ba-858f-425719e189d7",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q5\n",
    "ImportError is a built-in exception in Python that is raised when an import statement fails to find or \n",
    "load a module. It serves as a base class for various import-related exceptions.\n",
    "\n",
    "One specific exception derived from ImportError is ModuleNotFoundError. It is raised when a module cannot \n",
    "be found or imported. This exception was introduced in Python 3.6 as a more specific version of \n",
    "ImportError to clearly indicate that the module itself could not be located."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "7198348f-de5f-4cf9-938c-5963d23e693f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Import failed.\n",
      "Error: Module not found.\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError:\n",
    "    print(\"Error: Import failed.\")\n",
    "\n",
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError:\n",
    "    print(\"Error: Module not found.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "978ad1e3-c3bb-4b15-a60a-51ee7abfd56c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4c629369-0a0a-4371-a17e-e7abe3909fa8",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q6\n",
    "When it comes to exception handling in Python, here are some best practices to follow:\n",
    "\n",
    "1.Be specific in exception handling: Catch specific exceptions whenever possible rather than using a generic\n",
    "except block. This helps in identifying and handling the exact type of exception and avoids catching unrelated \n",
    "exceptions.\n",
    "\n",
    "2.Use multiple except blocks: If you need to handle different exceptions differently, use multiple except \n",
    "blocks to catch and handle each exception separately. This allows you to provide specific handling logic \n",
    "for different types of exceptions.\n",
    "\n",
    "3.Use finally block for cleanup: When you have cleanup code that should always run, regardless of whether \n",
    "an exception occurs or not, use a finally block. The code within the finally block will execute even if an \n",
    "exception is raised and not caught.\n",
    "\n",
    "4.Avoid bare except statements: Avoid using bare except statements (i.e., except: without specifying the\n",
    "exception type). It makes it difficult to understand the potential exceptions that can occur and can hide \n",
    "unexpected errors. Be explicit and mention the specific exceptions you want to catch.\n",
    "\n",
    "5.Handle exceptions at the right level: Handle exceptions at a level in your code where you can effectively \n",
    "handle and recover from them. Do not catch exceptions too broadly or at a level where you can't take appropriate \n",
    "action.\n",
    "\n",
    "6.Provide informative error messages: When catching and handling exceptions, provide informative error messages \n",
    "that help in identifying the cause of the exception. This can assist with debugging and troubleshooting.\n",
    "\n",
    "7.Avoid using exceptions for control flow: Exceptions should not be used for regular program flow or control flow.\n",
    "Exceptions are meant to handle exceptional and error conditions. Using them for normal program flow can make the \n",
    "code harder to understand and maintain.\n",
    "\n",
    "8.Use custom exceptions when necessary: Define and use custom exceptions when you have specific error conditions\n",
    "that are unique to your application or module. Custom exceptions can provide better clarity and allow you to \n",
    "handle those specific conditions separately.\n",
    "\n",
    "9.Log exceptions: Consider logging exceptions using a logging framework instead of just printing error messages. \n",
    "Logging allows you to capture and track exceptions for debugging and monitoring purposes.\n",
    "\n",
    "10.Test exception handling: Write test cases that cover different scenarios and ensure that the exception handling\n",
    "in your code behaves as expected. Test both the cases where exceptions are expected to be raised and where they \n",
    "should not be raised."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "17ac1423-b4db-4f13-88c1-2adecfa332df",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
